<?php
/**
 * Course
 */
class Course extends News
{
    private static $singular_name = 'Kurs';
    private static $plural_name = 'Kurse';
    //private static $icon = 'mysite/images/treffen.png';
    private static $can_be_root = false;
    private static $allowed_children = array();

    private static $db = array(
        'CourseTitle' => 'Varchar(255)',
        //'MenuTitle' => 'Varchar', // Not used
        'URLSegment' => 'Varchar(255)',
//        'CourseDateStart' => 'SS_Datetime',
//        'CourseDateEnd' => 'SS_Datetime',
        'Content' => 'HTMLText',
    );

    private static $has_one = array(
        'ContentImage' => 'Image',
        'HomepageSection' => 'SectionPage'
    );

    private static $many_many = array(
        'Sections' => 'SectionPage',
    );

    private static $summary_fields = array(
        'CourseTitle' => 'Kurstitel',
        'URLSegment' => 'URL-Segment',
        'SectionList' => 'Bereiche',
        'Thumbnail' => 'Bild',
    );

    /*public function getNiceNewsDate()
    {
        $date = new Date();
        $date->setValue($this->NewsDate);
        SS_Log::log($date, SS_Log::WARN);
        return $date->Format('d.m.Y');
    }*/

    public function News()
    {
        if(!$this->HomepageSectionID) return 'Nicht auf der Startseite.';
        elseif($this->HomepageSectionID) {
            return DataObject::get_by_id('SectionPage',$this->HomepageSectionID)->Title;
        }
    }

    public function SectionList ()
    {
        //SS_Log::log('getChildList - Children? '.$this->Children()->exists().' for ' .$this->Title,SS_Log::WARN);
        if($this->Sections()->exists()) {
            return implode(', ', $this->Sections()->column('Title'));
        }
    }

    public function getTitle()
    {
        return $this->CourseTitle;
    }

    public function getMenuTitle()
    {
        return $this->CourseTitle;
    }

    public function Thumbnail()
    {
        return $this->NewsImage()->SetHeight(50);
    }

    public function NewsSection()
    {
            return $this->HomepageSection()->Title;
    }

    public function getCMSFields() {

        $controller = Controller::curr();
        //SS_Log::log('controller='.$controller,SS_Log::WARN);

        $fields = parent::getCMSFields();
        // Remove "autogenerated" (by manymany relation) Sections tab
        $fields->removeByName('Sections');

        if($controller == 'NewsAdmin')
        {
            //News Main TAB
            $title = TextField::create('NewsTitle', $this->fieldLabel('NewsTitle'))->setDescription('Der Titel der News.');
            $fields->addFieldToTab('Root.Main', $title);
            $newsDate = DateField::create('NewsDate', $this->fieldLabel('NewsDate'))
                ->setConfig('dataformat', 'dd.MM.yyyy')
                ->setConfig('showcalendar', true);
            $newsDate->setDescription(sprintf('z.B. %s', Convert::raw2xml(Zend_Date::now()->toString('dd.MM.yyyy'))));
            $fields->addFieldToTab('Root.Main', $newsDate);
            //$fields->addFieldToTab('Root.News', LinkField::create('NewsLinkID', 'Link'));
            $fields->removeByName('NewsLinkID');
            $fields->addFieldToTab('Root.Main', DropdownField::create('HomepageSectionID',
                $this->fieldLabel('HomepageSection'), $this->Sections()->map('ID', 'Title'))
                ->setEmptyString('(Zur Anzeige bitte wählen)')
                ->setDescription('Wenn kein Bereich gewählt ist erscheint die News nicht auf der Startseite!')
             );
            $newsImage = new UploadField('NewsImage', $this->fieldLabel('NewsImage'));
            $newsImage->setConfig('allowedMaxFileNumber', 1);
            $newsImage->getValidator()->allowedExtensions = array('jpg', 'gif', 'png');
            $newsImage->setFolderName('news');
            $fields->addFieldToTab('Root.Main', $newsImage);
            $fields->addFieldToTab('Root.Main',
                HtmlEditorField::create('NewsContent', $this->fieldLabel('NewsContent'))
                ->setRows(3)
                ->setTargetLength(250, 50, 250)
                ->setDescription('Die maximale Textlänge ist begrenzt. Eingaben über 100% werden abgeschnitten.')
            );
            $fields->removeFieldsFromTab('Root.Main',array('CourseTitle','URLSegment','MenuTitle','CourseDateStart','CourseDateEnd','Content','ContentImage'));
        }
        if($controller == 'CourseAdmin')
        {
            //Course Main TAB
            $fields->removeByName('NewsLinkID');
            $fields->addFieldToTab('Root.Main', TextField::create('CourseTitle', $this->fieldLabel('CourseTitle'))
                ->setDescription('Der Titel des Kurses, Workshops oder der Veranstaltung.'));
            $fields->addFieldToTab('Root.Main', TextField::create('URLSegment', $this->fieldLabel('URLSegment'))
                ->setDescription('Wird beim Speichern generiert, bitte nur in vollem Bewusstsein ändern.'));
            //$fields->addFieldToTab('Root.Main', TextField::create('MenuTitle', $this->fieldLabel('MenuTitle'))
            //    ->setDescription('Wird automatisch vom Seitennamen übernommen, kann geändert werden.'));
            $fields->removeByName('MenuTitle');
            $map = DataObject::get('SectionPage')->map();
            /*foreach ($map as $key => $value) {
                SS_Log::log('key='.$key.' value='.$value,SS_Log::WARN);
            }*/
            $sectionCheck = CheckboxSetField::create('Sections','Bereiche', $map);
            $fields->addFieldToTab('Root.Main', $sectionCheck);
            /*
            $startDate = DatetimeField::create('CourseDateStart', $this->fieldLabel('CourseDateStart'))
                ->setConfig('datavalueformat', 'dd.MM.yyyy HH:mm');
            $startDate->getDateField()->setConfig('showcalendar', true);
            $startDate->getDateField()->setDescription(sprintf('z.B. %s', Convert::raw2xml(Zend_Date::now()->toString('dd.MM.yyyy'))));
            $startDate->getTimeField()->setDescription(sprintf('z.B. %s', Convert::raw2xml(Zend_Date::now()->toString('HH:mm'))));
            $fields->addFieldToTab('Root.Main', $startDate);
            $endDate = DatetimeField::create('CourseDateEnd', $this->fieldLabel('CourseDateEnd'))
                ->setConfig('datavalueformat', 'dd-MM-yyyy HH:mm');
            $endDate->getDateField()->setConfig('showcalendar', true);
            $endDate->getDateField()->setDescription(sprintf('z.B. %s', Convert::raw2xml(Zend_Date::now()->toString('dd.MM.yyyy'))));
            $endDate->getTimeField()->setDescription(sprintf('z.B. %s', Convert::raw2xml(Zend_Date::now()->toString('HH:mm'))));
            $fields->addFieldToTab('Root.Main', $endDate);
            */
            $contentImage = new UploadField('ContentImage', $this->fieldLabel('ContentImage'));
            $contentImage->setConfig('allowedMaxFileNumber', 1);
            $contentImage->getValidator()->allowedExtensions = array('jpg', 'gif', 'png');
            $contentImage->setFolderName('kurse');
            $fields->addFieldToTab('Root.Main', $contentImage);
            $fields->addFieldToTab('Root.Main', HtmlEditorField::create('Content', $this->fieldLabel('Content')));
            $fields->removeFieldsFromTab('Root.Main',array('NewsTitle','NewsContent','NewsImage','NewsLink','HomepageSectionID'));
        }

/*
        $config = GridFieldConfig_RelationEditor::create();
        $config->removeComponentsByType($config->getComponentByType('GridFieldAddNewButton'));
        $gridfield = GridField::create("Sections", "Bereich", $this->Sections(), $config);
        $fields->addFieldToTab('Root.Bereiche', $gridfield);
*/

        return $fields;
    }

    public function fieldLabels($includerelations = true) {
        $labels = parent::fieldLabels($includerelations);
        $labels['CourseTitle'] = 'Kursname';
        $labels['MenuTitle'] = 'Navigationsbezeichnung';
        $labels['URLSegment'] = 'URL-Segment';
        $labels['CourseDateStart'] = 'Kurs-Datum - Anfang';
        $labels['CourseDateEnd'] = 'Kurs-Datum - Ende';
        $labels['Content'] = 'Inhalt';
        $labels['NewsTitle'] = 'Schlagzeile';
        $labels['News'] = 'News';
        $labels['NewsImage'] = 'Bild';
        $labels['ContentImage'] = 'Bild';
        $labels['HomepageSection'] = 'Link';
        $labels['Sections'] = 'Bereiche';
        return $labels;
    }

    /**
     * Get news items
     *
     * @param int $offset
     * @param int $maxitems Max number of items to return
     * @return DataList
     */
    /*public static function Entries($offset=0, $maxitems=5) {
        $filters = array('HomepageSectionID:GreaterThan'=>'0');
        //->sort('Date DESC')
        return Course::get()->filter($filters)->limit($maxitems, $offset);
    }*/

    public function onBeforeWrite()
    {
        parent::onBeforeWrite();

        /*$filter = URLSegmentFilter::create();
        if (!$this->URLSegment) {
            $this->URLSegment = $this->CourseTitle;
        }
        $this->URLSegment = $filter->filter($this->URLSegment);
        if (!$this->URLSegment) {
            $this->URLSegment = uniqid();
        }
        $count = 2;
        while (static::get_by_url_segment($this->URLSegment, $this->ID)) {
            // add a -n to the URLSegment if it already existed
            $this->URLSegment = preg_replace('/-[0-9]+$/', null, $this->URLSegment) . '-' . $count;
            $count++;
        }*/
        // If there is no URLSegment set, generate one from Title
        if(!$this->URLSegment)
        {
            $this->URLSegment = $this->generateURLSegment($this->CourseTitle);
        }
        else if($this->isChanged('URLSegment'))
        {
            // Make sure the URLSegment is valid for use in a URL
            $segment = preg_replace('/[^A-Za-z0-9]+/','-',$this->URLSegment);
            $segment = preg_replace('/-+/','-',$segment);
            // If after sanitising there is no URLSegment, give it a reasonable default
            if(!$segment) {
                $segment = "item-$this->ID";
            }
            $this->URLSegment = $segment;
        }
        // Ensure that this object has a non-conflicting URLSegment value.
        $count = 2;
        $URLSegment = $this->URLSegment;
        $ID = $this->ID;
        while($this->LookForExistingURLSegment($URLSegment, $ID))
        {
            $URLSegment = preg_replace('/-[0-9]+$/', null, $URLSegment) . '-' . $count;
            $count++;
        }
        $this->URLSegment = $URLSegment;

        $this->addCourseNewsProperties();
    }

    /*public function onAfterWrite()
    {
        parent::onAfterWrite();

    }*/

    /**
     * Check if there is already a DOAP with this URLSegment
     */
    public function LookForExistingURLSegment($URLSegment, $ID)
    {
        return Course::get()->filter(
            'URLSegment',$URLSegment
        )->exclude('ID', $ID)->exists();
    }

    /**
     * Generate a URL segment based on the title provided.
     *
     * If {@link Extension}s wish to alter URL segment generation, they can do so by defining
     * updateURLSegment(&$url, $title).  $url will be passed by reference and should be modified.
     * $title will contain the title that was originally used as the source of this generated URL.
     * This lets extensions either start from scratch, or incrementally modify the generated URL.
     *
     * @param string $title Page title.
     * @return string Generated url segment
     */
    public function generateURLSegment($title)
    {
        $filter = URLSegmentFilter::create();
        $t = $filter->filter($title);

        // Fallback to generic page name if path is empty (= no valid, convertable characters)
        if(!$t || $t == '-' || $t == '-1') $t = "page-$this->ID";

        // Hook for extensions
        $this->extend('updateURLSegment', $t, $title);

        return $t;
    }

    public function addCourseNewsProperties()
    {
        //SS_Log::log('addNewsProperties(), for '.$this->CourseTitle,SS_Log::WARN);
        // NewsTitle
        if(empty($this->NewsTitle)) $this->NewsTitle = $this->CourseTitle;
        // NewsDate
        if(empty($this->NewsDate)) $this->NewsDate = $this->CourseDateStart;
        // NewsContent
        if(empty($this->NewsContent)) $this->NewsContent = $this->dbobject('Content')->FirstParagraph();
        // NewsImage
        if(empty($this->NewsImageID)) $this->NewsImageID = $this->ContentImageID;
    }

    /**
     * @return string
     */
    public function Link() {
        //SS_Log::log('Link() for '.$this->Title .' count='.$this->Sections()->count(),SS_Log::WARN);
        if($this->isInDB()) {
            //SS_Log::log(' Link()  controller = '.Controller::curr(),SS_Log::WARN);
            // For HomePage
            if(Controller::curr() == 'HomePage_Controller') {
                if($this->HomepageSectionID) {
                    $section = DataObject::get_by_id('SectionPage',$this->HomepageSectionID);
                    //SS_Log::log('Homepage? ='.$section->Link(),SS_Log::WARN);
                    return Controller::join_links($section->Link(),'kurs',$this->URLSegment);
                }
            }
            // SectionPage
            else {
                // Course is just linked once
                if($this->Sections()->count() == 1) {
                    return Controller::join_links($this->Sections()->First()->Link(),'kurs',$this->URLSegment);
                }
                // Course is linked several times
                elseif($this->Sections()->count() > 1) {
                    foreach ($this->Sections() as $section) {
                        // Create link for current context
                        if ($section->Link() == Controller::curr()->Link()) {
                            return Controller::join_links($section->Link(),'kurs',$this->URLSegment);
                        }
                    } //foreach
                }
            }
        }
        return '';
    }

    /**
     * @var array
     */
    protected static $_cached_get_by_url = array();
    /**
     * @param $str
     * @return Course|Boolean
     */
    public static function get_by_url_segment($str, $excludeID = null) {
        if (!isset(static::$_cached_get_by_url[$str])) {
            $list = static::get()->filter('URLSegment', $str);
            if ($excludeID) {
                $list = $list->exclude('ID', $excludeID);
            }
            $obj = $list->First();
            static::$_cached_get_by_url[$str] = ($obj && $obj->exists()) ? $obj : false;
        }
        return static::$_cached_get_by_url[$str];
    }

    public function canDelete($member = null) {
        //Avoid deleting Course as from within NewsAdmin
        if (Controller::curr() == 'NewsAdmin') return false;
        else return Permission::check('SITETREE_EDIT_ALL', 'any', $member);
    }

}
