---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'jimev-theme'

# Display template filenames as comments in the html output
  source_file_comments: true
# Enable Fragment Link rewriting (hashlinks)
#  rewrite_hash_links: false
