---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'jimev-theme'

# Display template filenames as comments in the html output
  source_file_comments: true
# Enable Fragment Link rewriting (hashlinks)
#  rewrite_hash_links: false

# Rescale upload to max-width/-height
#ScaledUploads:
#  max-width: 1600
#  max-height: 1200
#  auto-rotate: 0
#  bypass: 0

# General Quality GD
GDBackend:
  default_quality: 95

# Jonom/Focuspoint
FocusPointImage:
  flush_on_change: true

# Email
Email:
  admin_email: info@jimev.de

# Inject Image with https://github.com/jonom/silverstripe-focuspoint/
Injector:
  Image:
  class: FPImage

Upload_Validator:
  default_max_file_size:
    '[image]': '1000'
    'jpg': '1000'
